add solution for 06-deep-Vue 07-NodesPagination
js-tasks-ru/vue-20200925-2_artmar14 pull request #30
Opened 2021-02-17 21:06 UTC by artm4r

2021-02-17 21:06 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-02-17 21:27 UTC, ShGKme requested changes
Решение работает, если содержимое не меняется, так как `$slots` не реактивный...

2021-02-17 21:27 UTC, ShGKme commented on 06-deep-vue/07-NodesPagination/components/NodesPagination.vue
> +  },
`this.$slots` - не реактивный. Это вычисляемое свойство не будет обновлено, когда обновится содержимое, переданное через слот. Если хочется вынести содержимое из рендер функции, то это можно сделать методом.

2021-02-18 11:11 UTC, artm4r commented on 06-deep-vue/07-NodesPagination/components/NodesPagination.vue
> +  },
Спасибо, подумаю сейчас как это правильно решить)

2021-02-18 12:22 UTC, ShGKme commented on 06-deep-vue/07-NodesPagination/components/NodesPagination.vue
> +  },
Посчитать это прямо в рендер функции, либо вынести в метод, а не вычисляемое свойство, либо в вычисляемом свойстве возвращать функцию)

2021-02-18 13:31 UTC, artm4r reviewed
Использовал метод вместо вычисляемого свойства.

2021-02-18 19:30 UTC, ShGKme approved these changes
Принято 👍

2021-02-18 19:30 UTC, merged